Assignment 10
Koden simulerar aktiedata för 100 dagar så man kan öva analys i Pandas.
Explore the attributes and methods we covered in the Pandas tutorial .ipynb file (shared in Module 6) using the data object below

In [2]:
# generating data
import pandas as pd
import numpy as np

# Sätter ett startvärde för slumpen
# Det gör att samma slumpade data skapas varje gång man kör koden.
np.random.seed(42)

# Number of samples (vi vill ha 100 rader data).
n = 100

# Generate data/skapas en tabell
data = pd.DataFrame({
    # Skapar datum från 1 januari 2024 och 100 dagar framåt, varje dag
    "Date": pd.date_range(start="2024-01-01", periods=n, freq="D"),
    # Väljer slumpmässigt aktienamn:AAPL = Apple, GOOG = Google,TSLA = Tesla, AMZN = Amazon
    # 100 slumpade val.
    "Stock": np.random.choice(["AAPL", "GOOG", "TSLA", "AMZN"], size=n),
    # Skapar n slumpade öppnings- och stängningspriser mellan 100 och 500, med 2 decimaler
    "Open_Price": np.round(np.random.uniform(100, 500, size=n), 2),
    "Close_Price": np.round(np.random.uniform(100, 500, size=n), 2),
    # Skapar slumpad handelsvolym (hur många aktier som handlades) mellan 1000 och 9999
    "Volume": np.random.randint(1000, 10000, size=n),
    # Väljer slumpmässigt sektor: Tech = Teknik, Retail = Handel, Automotive = Bilar
    "Sector": np.random.choice(["Tech", "Retail", "Automotive"], size=n)
})

print("Indata\n", data, "\n")

Indata
          Date Stock  Open_Price  Close_Price  Volume      Sector
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
1  2024-01-02  AMZN      410.05       195.82    1980  Automotive
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
3  2024-01-04  TSLA      457.93       295.78    7102      Retail
4  2024-01-05  TSLA      339.16       494.26    2184        Tech
..        ...   ...         ...          ...     ...         ...
95 2024-04-05  GOOG      114.75       471.33    5070        Tech
96 2024-04-06  GOOG      343.83       271.27    1580        Tech
97 2024-04-07  AMZN      301.07       486.66    8004  Automotive
98 2024-04-08  GOOG      120.59       485.45    9130        Tech
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive

[100 rows x 6 columns]

# Nivå 1 – Grunderna

In [4]:
## 1. Visa de första 5 raderna
print("1. De första raderna:\n", data.head(), "\n")

1. De första raderna:
         Date Stock  Open_Price  Close_Price  Volume      Sector
0 2024-01-01  TSLA      487.83       463.31    1190      Retail
1 2024-01-02  AMZN      410.05       195.82    1980  Automotive
2 2024-01-03  AAPL      475.80       157.96    3975        Tech
3 2024-01-04  TSLA      457.93       295.78    7102      Retail
4 2024-01-05  TSLA      339.16       494.26    2184        Tech

In [5]:
## 2. Visa kolumnens namn
print("2. Namnen på kolumner: \n", data.columns, "\n")

2. Namnen på kolumner:
 Index(['Date', 'Stock', 'Open_Price', 'Close_Price', 'Volume', 'Sector'], dtype='str')

In [7]:
## 3. Visa kolumnen Sector för alla aktier
print("3. Sector:\n", data["Sector"], "\n")

3. Sector:
 0         Retail
1     Automotive
2           Tech
3         Retail
4           Tech
         ...
95          Tech
96          Tech
97    Automotive
98          Tech
99    Automotive
Name: Sector, Length: 100, dtype: str

In [9]:
## 4. Visa kolumnerna Sector och Stock för alla aktier
print("4. Stock och Sector:\n", data[["Stock","Sector"]], "\n")

4. Stock och Sector:
    Stock      Sector
0   TSLA      Retail
1   AMZN  Automotive
2   AAPL        Tech
3   TSLA      Retail
4   TSLA        Tech
..   ...         ...
95  GOOG        Tech
96  GOOG        Tech
97  AMZN  Automotive
98  GOOG        Tech
99  AAPL  Automotive

[100 rows x 2 columns]

In [10]:
## 5. Hur många rader finns?
print("4. Antal rader:", len(data), "\n")

4. Antal rader: 100

In [37]:
# 6. Visa enstaka raden
print(data.iloc[0])    # 1-a
print("\n")
# Hitta alla rader där Stock = AAPL
print("Alla rader som handlar om Apple:\n", data.loc[data["Stock"] == "AAPL"]) 
print("\n")
# Hitta alla rader där Sector = Tech
print("Alla rader som visar Teknik som sektor:\n", data.loc[data["Sector"] == "Tech"]) 
print("\n")
# Hitta rader där Volume är större än 5000
print("Alla rader som visar volym > 9000:\n", data.loc[data["Volume"] > 9000])
print("\n")
# Hitta rader i kolumnen Stock där finns bokstavskombination AA
print("Alla rader som innehåller 'AA':\n", data.loc[data["Stock"].str.contains("AA")])

Date           2024-01-01 00:00:00
Stock                         TSLA
Open_Price                  487.83
Close_Price                 463.31
Volume                        1190
Sector                      Retail
Name: 0, dtype: object


Alla rader som handlar om Apple:
          Date Stock  Open_Price  Close_Price  Volume      Sector
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
6  2024-01-07  AAPL      135.40       368.85    4394      Retail
7  2024-01-08  AAPL      178.39       404.65    9319        Tech
15 2024-01-16  AAPL      317.08       434.12    4863      Retail
21 2024-01-22  AAPL      179.49       106.64    1154        Tech
30 2024-01-31  AAPL      445.24       236.43    3806      Retail
31 2024-02-01  AAPL      349.32       145.39    1537  Automotive
35 2024-02-05  AAPL      230.07       363.99    7971        Tech
37 2024-02-07  AAPL      355.02       322.08    3950      Retail
38 2024-02-08  AAPL      454.89       311.86    8992        Tech
57 2024-02-27  AAPL      402.22       365.40    3491      Retail
59 2024-02-29  AAPL      130.79       164.32    6691  Automotive
62 2024-03-03  AAPL      471.88       360.78    6222  Automotive
63 2024-03-04  AAPL      423.25       189.71    6315        Tech
67 2024-03-08  AAPL      174.63       398.60    5142      Retail
72 2024-03-13  AAPL      227.20       137.47    5465        Tech
74 2024-03-15  AAPL      191.17       206.08    2693      Retail
82 2024-03-23  AAPL      147.95       330.76    3838        Tech
87 2024-03-28  AAPL      381.21       109.73    2081  Automotive
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive


Alla rader som visar Teknik som sektor:
          Date Stock  Open_Price  Close_Price  Volume Sector
2  2024-01-03  AAPL      475.80       157.96    3975   Tech
4  2024-01-05  TSLA      339.16       494.26    2184   Tech
5  2024-01-06  AMZN      468.75       196.82    4327   Tech
7  2024-01-08  AAPL      178.39       404.65    9319   Tech
9  2024-01-10  GOOG      230.13       391.29    6854   Tech
13 2024-01-14  TSLA      242.70       314.31    2895   Tech
16 2024-01-17  AMZN      156.37       228.31    8455   Tech
18 2024-01-19  AMZN      129.82       116.31    2686   Tech
21 2024-01-22  AAPL      179.49       106.64    1154   Tech
26 2024-01-27  GOOG      408.51       376.38    8343   Tech
33 2024-02-03  GOOG      125.42       450.94    2841   Tech
34 2024-02-04  GOOG      224.39       203.18    9716   Tech
35 2024-02-05  AAPL      230.07       363.99    7971   Tech
38 2024-02-08  AAPL      454.89       311.86    8992   Tech
42 2024-02-12  GOOG      404.31       460.17    9173   Tech
43 2024-02-13  AMZN      324.51       353.24    5495   Tech
44 2024-02-14  AMZN      408.39       235.61    7002   Tech
47 2024-02-17  TSLA      271.02       458.84    1853   Tech
49 2024-02-19  GOOG      143.16       411.95    4769   Tech
50 2024-02-20  TSLA      112.57       356.81    1574   Tech
53 2024-02-23  AMZN      303.43       459.42    7457   Tech
54 2024-02-24  TSLA      463.03       342.57    8509   Tech
58 2024-02-28  TSLA      191.52       102.02    4124   Tech
63 2024-03-04  AAPL      423.25       189.71    6315   Tech
65 2024-03-06  GOOG      448.58       194.90    1876   Tech
72 2024-03-13  AAPL      227.20       137.47    5465   Tech
75 2024-03-16  GOOG      270.84       197.60    5752   Tech
77 2024-03-18  AMZN      444.29       257.24    1830   Tech
79 2024-03-20  AMZN      304.30       352.46    9932   Tech
80 2024-03-21  TSLA      266.96       417.92    9308   Tech
81 2024-03-22  AMZN      188.84       301.05    6949   Tech
82 2024-03-23  AAPL      147.95       330.76    3838   Tech
83 2024-03-24  AMZN      235.05       297.01    2150   Tech
85 2024-03-26  TSLA      229.28       388.98    2931   Tech
86 2024-03-27  GOOG      307.52       212.31    2664   Tech
88 2024-03-29  AMZN      245.45       358.19    1512   Tech
91 2024-04-01  AMZN      200.71       481.57    1559   Tech
95 2024-04-05  GOOG      114.75       471.33    5070   Tech
96 2024-04-06  GOOG      343.83       271.27    1580   Tech
98 2024-04-08  GOOG      120.59       485.45    9130   Tech


Alla rader som visar volym > 9000:
          Date Stock  Open_Price  Close_Price  Volume  Sector
7  2024-01-08  AAPL      178.39       404.65    9319    Tech
24 2024-01-25  AMZN      382.74       358.07    9096  Retail
34 2024-02-04  GOOG      224.39       203.18    9716    Tech
42 2024-02-12  GOOG      404.31       460.17    9173    Tech
76 2024-03-17  AMZN      427.21       489.20    9311  Retail
79 2024-03-20  AMZN      304.30       352.46    9932    Tech
80 2024-03-21  TSLA      266.96       417.92    9308    Tech
98 2024-04-08  GOOG      120.59       485.45    9130    Tech


Alla rader som innehåller 'AA':
          Date Stock  Open_Price  Close_Price  Volume      Sector
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
6  2024-01-07  AAPL      135.40       368.85    4394      Retail
7  2024-01-08  AAPL      178.39       404.65    9319        Tech
15 2024-01-16  AAPL      317.08       434.12    4863      Retail
21 2024-01-22  AAPL      179.49       106.64    1154        Tech
30 2024-01-31  AAPL      445.24       236.43    3806      Retail
31 2024-02-01  AAPL      349.32       145.39    1537  Automotive
35 2024-02-05  AAPL      230.07       363.99    7971        Tech
37 2024-02-07  AAPL      355.02       322.08    3950      Retail
38 2024-02-08  AAPL      454.89       311.86    8992        Tech
57 2024-02-27  AAPL      402.22       365.40    3491      Retail
59 2024-02-29  AAPL      130.79       164.32    6691  Automotive
62 2024-03-03  AAPL      471.88       360.78    6222  Automotive
63 2024-03-04  AAPL      423.25       189.71    6315        Tech
67 2024-03-08  AAPL      174.63       398.60    5142      Retail
72 2024-03-13  AAPL      227.20       137.47    5465        Tech
74 2024-03-15  AAPL      191.17       206.08    2693      Retail
82 2024-03-23  AAPL      147.95       330.76    3838        Tech
87 2024-03-28  AAPL      381.21       109.73    2081  Automotive
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive

In [39]:
## 7. Flera villkor samtidigt
# Stock = AAPL och Volume > 5000
print("När aktier Apple såldes fler än 50000?\n", data.loc[(data["Stock"] == "AAPL") & (data["Volume"] > 5000)])

När aktier Apple såldes fler än 50000?
          Date Stock  Open_Price  Close_Price  Volume      Sector
7  2024-01-08  AAPL      178.39       404.65    9319        Tech
35 2024-02-05  AAPL      230.07       363.99    7971        Tech
38 2024-02-08  AAPL      454.89       311.86    8992        Tech
59 2024-02-29  AAPL      130.79       164.32    6691  Automotive
62 2024-03-03  AAPL      471.88       360.78    6222  Automotive
63 2024-03-04  AAPL      423.25       189.71    6315        Tech
67 2024-03-08  AAPL      174.63       398.60    5142      Retail
72 2024-03-13  AAPL      227.20       137.47    5465        Tech

In [40]:
# 8. Visa bara vissa kolumner samtidigt
# t.ex aktier Apple med datum och öppningspris
print("Vilka öppningspriser hade aktier Apple?\n", data.loc[data["Stock"] == "AAPL", ["Date", "Open_Price"]])

Vilka öppningspriser hade aktier Apple?
          Date  Open_Price
2  2024-01-03      475.80
6  2024-01-07      135.40
7  2024-01-08      178.39
15 2024-01-16      317.08
21 2024-01-22      179.49
30 2024-01-31      445.24
31 2024-02-01      349.32
35 2024-02-05      230.07
37 2024-02-07      355.02
38 2024-02-08      454.89
57 2024-02-27      402.22
59 2024-02-29      130.79
62 2024-03-03      471.88
63 2024-03-04      423.25
67 2024-03-08      174.63
72 2024-03-13      227.20
74 2024-03-15      191.17
82 2024-03-23      147.95
87 2024-03-28      381.21
99 2024-04-09      211.46

In [41]:
# 9. Om du vill hitta något ord i hela tabellen, inte bara en kolumn
# För att hitta rader som innehåller något:data.loc[data["kolumn"].str.contains("text")]
data.loc[data.astype(str).apply(lambda x: x.str.contains("AAPL")).any(axis=1)]

         Date Stock  Open_Price  Close_Price  Volume      Sector
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
6  2024-01-07  AAPL      135.40       368.85    4394      Retail
7  2024-01-08  AAPL      178.39       404.65    9319        Tech
15 2024-01-16  AAPL      317.08       434.12    4863      Retail
21 2024-01-22  AAPL      179.49       106.64    1154        Tech
30 2024-01-31  AAPL      445.24       236.43    3806      Retail
31 2024-02-01  AAPL      349.32       145.39    1537  Automotive
35 2024-02-05  AAPL      230.07       363.99    7971        Tech
37 2024-02-07  AAPL      355.02       322.08    3950      Retail
38 2024-02-08  AAPL      454.89       311.86    8992        Tech
57 2024-02-27  AAPL      402.22       365.40    3491      Retail
59 2024-02-29  AAPL      130.79       164.32    6691  Automotive
62 2024-03-03  AAPL      471.88       360.78    6222  Automotive
63 2024-03-04  AAPL      423.25       189.71    6315        Tech
67 2024-03-08  AAPL      174.63       398.60    5142      Retail
72 2024-03-13  AAPL      227.20       137.47    5465        Tech
74 2024-03-15  AAPL      191.17       206.08    2693      Retail
82 2024-03-23  AAPL      147.95       330.76    3838        Tech
87 2024-03-28  AAPL      381.21       109.73    2081  Automotive
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive

In [42]:
## 10. Visa information om tabellen
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         100 non-null    datetime64[us]
 1   Stock        100 non-null    str
 2   Open_Price   100 non-null    float64
 3   Close_Price  100 non-null    float64
 4   Volume       100 non-null    int32
 5   Sector       100 non-null    str
dtypes: datetime64[us](1), float64(2), int32(1), str(2)
memory usage: 4.4 KB

In [43]:
## 11. Visa statistik
print("6. Statistik\n", data.describe(),"\n")

6. Statistik
                       Date  Open_Price  Close_Price       Volume
count                  100  100.000000   100.000000   100.000000
mean   2024-02-19 12:00:00  294.547400   306.682900  5384.630000
min    2024-01-01 00:00:00  102.210000   102.020000  1004.000000
25%    2024-01-25 18:00:00  197.670000   196.510000  2881.500000
50%    2024-02-19 12:00:00  293.205000   324.700000  5480.000000
75%    2024-03-15 06:00:00  408.607500   400.112500  7731.500000
max    2024-04-09 00:00:00  494.750000   494.260000  9932.000000
std                    NaN  120.322026   119.340534  2622.187061

# Nivå 2 – Filtrering

In [45]:
## 12. Aktier med öppningspriset > 450
print(" Öppningspri > 450:\n", data[data["Open_Price"] > 450],"\n")

 Öppningspris > 450:
          Date Stock  Open_Price  Close_Price  Volume      Sector
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
3  2024-01-04  TSLA      457.93       295.78    7102      Retail
5  2024-01-06  AMZN      468.75       196.82    4327        Tech
19 2024-01-20  TSLA      494.75       336.36    4009      Retail
38 2024-02-08  AAPL      454.89       311.86    8992        Tech
54 2024-02-24  TSLA      463.03       342.57    8509        Tech
62 2024-03-03  AAPL      471.88       360.78    6222  Automotive
68 2024-03-09  AMZN      457.02       359.85    7966      Retail
71 2024-03-12  GOOG      458.44       327.32    7799  Automotive
84 2024-03-25  TSLA      477.16       178.10    8560      Retail
89 2024-03-30  GOOG      488.71       170.84    8805  Automotive
90 2024-03-31  AMZN      484.98       476.18    6237      Retail

In [19]:
## 13. Aktier Tesla 
print(" \nTSLA:\n", data[data["Stock"] == "TSLA"],"\n")

TSLA:
          Date Stock  Open_Price  Close_Price  Volume      Sector
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
3  2024-01-04  TSLA      457.93       295.78    7102      Retail
4  2024-01-05  TSLA      339.16       494.26    2184        Tech
8  2024-01-09  TSLA      118.09       195.06    2816  Automotive
10 2024-01-11  TSLA      255.47       247.11    7709      Retail
11 2024-01-12  TSLA      208.54       352.92    1569      Retail
12 2024-01-13  TSLA      431.50       353.41    6442      Retail
13 2024-01-14  TSLA      242.70       314.31    2895        Tech
19 2024-01-20  TSLA      494.75       336.36    4009      Retail
39 2024-02-09  TSLA      288.89       196.74    5780  Automotive
40 2024-02-10  TSLA      147.84       137.24    3368      Retail
41 2024-02-11  TSLA      385.30       458.89    7655  Automotive
47 2024-02-17  TSLA      271.02       458.84    1853        Tech
50 2024-02-20  TSLA      112.57       356.81    1574        Tech
52 2024-02-22  TSLA      225.74       164.65    7293  Automotive
54 2024-02-24  TSLA      463.03       342.57    8509        Tech
58 2024-02-28  TSLA      191.52       102.02    4124        Tech
60 2024-03-01  TSLA      215.90       319.49    4051      Retail
61 2024-03-02  TSLA      164.49       376.76    1004  Automotive
64 2024-03-05  TSLA      353.36       384.87    5869      Retail
78 2024-03-19  TSLA      102.78       456.82    6177  Automotive
80 2024-03-21  TSLA      266.96       417.92    9308        Tech
84 2024-03-25  TSLA      477.16       178.10    8560      Retail
85 2024-03-26  TSLA      229.28       388.98    2931        Tech

In [20]:
## 14. Items med stängningspriser > 400
print(" Items med Close_price> 450:\n", data[data["Close_Price"] > 450],"\n")

 Items med Close_price> 450:
          Date Stock  Open_Price  Close_Price  Volume      Sector
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
4  2024-01-05  TSLA      339.16       494.26    2184        Tech
28 2024-01-29  AMZN      243.39       474.69    6596  Automotive
32 2024-02-02  AMZN      232.36       469.88    6986      Retail
33 2024-02-03  GOOG      125.42       450.94    2841        Tech
41 2024-02-11  TSLA      385.30       458.89    7655  Automotive
42 2024-02-12  GOOG      404.31       460.17    9173        Tech
47 2024-02-17  TSLA      271.02       458.84    1853        Tech
48 2024-02-18  GOOG      110.17       454.83    5146  Automotive
53 2024-02-23  AMZN      303.43       459.42    7457        Tech
76 2024-03-17  AMZN      427.21       489.20    9311      Retail
78 2024-03-19  TSLA      102.78       456.82    6177  Automotive
90 2024-03-31  AMZN      484.98       476.18    6237      Retail
91 2024-04-01  AMZN      200.71       481.57    1559        Tech
92 2024-04-02  GOOG      298.90       465.95    4672  Automotive
95 2024-04-05  GOOG      114.75       471.33    5070        Tech
97 2024-04-07  AMZN      301.07       486.66    8004  Automotive
98 2024-04-08  GOOG      120.59       485.45    9130        Tech

In [27]:
## 15. Har open-price < 400 och har volym över 1000
#data[(data["Open_price"] >400) & (data["Close_pris"] <300)]
#print(data)

In [24]:
## 16. Tillhör inte kategori AMZN
not_AMZN=data[data["Stock"] != "AMZN"]
print(not_AMZN)

         Date Stock  Open_Price  Close_Price  Volume      Sector
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
2  2024-01-03  AAPL      475.80       157.96    3975        Tech
3  2024-01-04  TSLA      457.93       295.78    7102      Retail
4  2024-01-05  TSLA      339.16       494.26    2184        Tech
6  2024-01-07  AAPL      135.40       368.85    4394      Retail
..        ...   ...         ...          ...     ...         ...
94 2024-04-04  GOOG      213.94       106.18    4343      Retail
95 2024-04-05  GOOG      114.75       471.33    5070        Tech
96 2024-04-06  GOOG      343.83       271.27    1580        Tech
98 2024-04-08  GOOG      120.59       485.45    9130        Tech
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive

[70 rows x 6 columns]

# Nivå 3 – Sortering och analys

In [46]:
## 17. Sortera efter öppningspriset
data.sort_values("Open_Price")

         Date Stock  Open_Price  Close_Price  Volume      Sector
22 2024-01-23  GOOG      102.21       304.84    2409  Automotive
78 2024-03-19  TSLA      102.78       456.82    6177  Automotive
48 2024-02-18  GOOG      110.17       454.83    5146  Automotive
50 2024-02-20  TSLA      112.57       356.81    1574        Tech
95 2024-04-05  GOOG      114.75       471.33    5070        Tech
..        ...   ...         ...          ...     ...         ...
84 2024-03-25  TSLA      477.16       178.10    8560      Retail
90 2024-03-31  AMZN      484.98       476.18    6237      Retail
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
89 2024-03-30  GOOG      488.71       170.84    8805  Automotive
19 2024-01-20  TSLA      494.75       336.36    4009      Retail

[100 rows x 6 columns]

In [48]:
## 18. Sortera högsta volymen först
data.sort_values("Volume", ascending=False)

         Date Stock  Open_Price  Close_Price  Volume      Sector
79 2024-03-20  AMZN      304.30       352.46    9932        Tech
34 2024-02-04  GOOG      224.39       203.18    9716        Tech
7  2024-01-08  AAPL      178.39       404.65    9319        Tech
76 2024-03-17  AMZN      427.21       489.20    9311      Retail
80 2024-03-21  TSLA      266.96       417.92    9308        Tech
..        ...   ...         ...          ...     ...         ...
31 2024-02-01  AAPL      349.32       145.39    1537  Automotive
88 2024-03-29  AMZN      245.45       358.19    1512        Tech
0  2024-01-01  TSLA      487.83       463.31    1190      Retail
21 2024-01-22  AAPL      179.49       106.64    1154        Tech
61 2024-03-02  TSLA      164.49       376.76    1004  Automotive

[100 rows x 6 columns]

In [55]:
## 19. Medelpriset 
print("Medelpriset vid stängning:", round(data["Close_Price"].mean(),1))

Medelpriset vid stängning: 306.7

In [52]:
## 20. Högsta antal sålda aktier
print(" Högsta antalet dagligen sålda aktier:", data["Volume"].max())

 Högsta anatlet dagligen sålda aktier: 9932

In [57]:
## 21. Lägsta antal sålda aktier
print(" Längsta antalet dagligen sålda aktier:",data["Volume"].min())

 Längsta antalet dagligen sålda aktier: 1004

# Nivå 4 – Skapa kolumner

In [61]:
## 22. Ny kolumn skatt (22%)
data["Skatt"] = round((data["Close_Price"]* data["Volume"])* 0.22,1)
print("Nydata\n", data, "\n")

Nydata
          Date Stock  Open_Price  Close_Price  Volume      Sector     Skatt
0  2024-01-01  TSLA      487.83       463.31    1190      Retail  121294.6
1  2024-01-02  AMZN      410.05       195.82    1980  Automotive   85299.2
2  2024-01-03  AAPL      475.80       157.96    3975        Tech  138136.0
3  2024-01-04  TSLA      457.93       295.78    7102      Retail  462138.5
4  2024-01-05  TSLA      339.16       494.26    2184        Tech  237482.0
..        ...   ...         ...          ...     ...         ...       ...
95 2024-04-05  GOOG      114.75       471.33    5070        Tech  525721.5
96 2024-04-06  GOOG      343.83       271.27    1580        Tech   94293.5
97 2024-04-07  AMZN      301.07       486.66    8004  Automotive  856949.9
98 2024-04-08  GOOG      120.59       485.45    9130        Tech  975074.9
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive  402524.4

[100 rows x 7 columns]

In [88]:
## 20. Nettoinkomst efter skatt
data["Netto"] = ((data["Close_Price"]* data["Volume"]) * 0.78)/1000
print("Nettoinkomst efter skatt, tkr\n", data, "\n")

Nettoinkomst efter skatt, tkr
          Date Stock  Open_Price  Close_Price  Volume      Sector    Avgift  \
0  2024-01-01  TSLA      487.83       463.31    1190      Retail  121294.6
1  2024-01-02  AMZN      410.05       195.82    1980  Automotive   85299.2
2  2024-01-03  AAPL      475.80       157.96    3975        Tech  138136.0
3  2024-01-04  TSLA      457.93       295.78    7102      Retail  462138.5
4  2024-01-05  TSLA      339.16       494.26    2184        Tech  237482.0
..        ...   ...         ...          ...     ...         ...       ...
95 2024-04-05  GOOG      114.75       471.33    5070        Tech  525721.5
96 2024-04-06  GOOG      343.83       271.27    1580        Tech   94293.5
97 2024-04-07  AMZN      301.07       486.66    8004  Automotive  856949.9
98 2024-04-08  GOOG      120.59       485.45    9130        Tech  975074.9
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive  402524.4

          Netto  Över 500 000:\n  Över 500 000
0    430.044342            False         False
1    302.424408            False         False
2    489.754980            False         False
3   1638.491057             True          True
4    841.981795             True          True
..          ...              ...           ...
95  1863.921618             True          True
96   334.313148            False         False
97  3038.276779             True          True
98  3457.083630             True          True
99  1427.131992             True          True

[100 rows x 10 columns]

In [85]:
## 21. Är över 30?
data["Över 500 000"] = data["Netto"] > 500
print("Netto över 500 000 kr:\n", data)

Netto över 500 000 kr:
          Date Stock  Open_Price  Close_Price  Volume      Sector    Avgift  \
0  2024-01-01  TSLA      487.83       463.31    1190      Retail  121294.6
1  2024-01-02  AMZN      410.05       195.82    1980  Automotive   85299.2
2  2024-01-03  AAPL      475.80       157.96    3975        Tech  138136.0
3  2024-01-04  TSLA      457.93       295.78    7102      Retail  462138.5
4  2024-01-05  TSLA      339.16       494.26    2184        Tech  237482.0
..        ...   ...         ...          ...     ...         ...       ...
95 2024-04-05  GOOG      114.75       471.33    5070        Tech  525721.5
96 2024-04-06  GOOG      343.83       271.27    1580        Tech   94293.5
97 2024-04-07  AMZN      301.07       486.66    8004  Automotive  856949.9
98 2024-04-08  GOOG      120.59       485.45    9130        Tech  975074.9
99 2024-04-09  AAPL      211.46       441.20    4147  Automotive  402524.4

          Netto  Över 500 000:\n  Över 500 000
0    430.044342            False         False
1    302.424408            False         False
2    489.754980            False         False
3   1638.491057             True          True
4    841.981795             True          True
..          ...              ...           ...
95  1863.921618             True          True
96   334.313148            False         False
97  3038.276779             True          True
98  3457.083630             True          True
99  1427.131992             True          True

[100 rows x 10 columns]

# Nivå 5 – Grupp och riktig analys

In [77]:
## 22. Medelpris vid stängninhgen per stock
print("Aktiers medelpris vis stängningen per namnet:\n", round(data.groupby("Stock")["Close_Price"].mean(),2))

Aktiers medelpris vis stängningen per namnet:
 Stock
AAPL    277.80
AMZN    304.51
GOOG    314.76
TSLA    324.72
Name: Close_Price, dtype: float64

In [78]:
## 23. Antal aktier per sektor
data["Sector"].value_counts()

Sector
Tech          40
Retail        34
Automotive    26
Name: count, dtype: int64

In [79]:
# Bonusutmaning
## 24. Vilken dag såldes det högsta antal aktier?
data.loc[data["Volume"].idxmax()]

Date               2024-03-20 00:00:00
Stock                             AMZN
Open_Price                       304.3
Close_Price                     352.46
Volume                            9932
Sector                            Tech
Skatt                         770139.2
Netto                      2730.493522
Över 500 000:\n                   True
Name: 79, dtype: object

In [ ]:
## 25. Vad är snittpriset för aktier som över 30?
#data[data["Ålder"] > 30]["Lön"].mean()

# Nivå 5

In [83]:
# data cleaning
data = data.dropna()                     # remove missing rows
#data["Skatt"] = data["Skatt"].fillna(0)      # fill missing values
#data = data.drop_duplicates()
#data = data.rename(columns={"Skatt": "Avgift"})
data

,Date,Stock,Open_Price,Close_Price,Volume,Sector,Avgift,Netto,Över 500 000:\n,Över 500 000
0,2024-01-01,TSLA,487.83,463.31,1190,Retail,121294.6,430.044342,False,False
1,2024-01-02,AMZN,410.05,195.82,1980,Automotive,85299.2,302.424408,False,False
2,2024-01-03,AAPL,475.80,157.96,3975,Tech,138136.0,489.754980,False,False
3,2024-01-04,TSLA,457.93,295.78,7102,Retail,462138.5,1638.491057,True,True
4,2024-01-05,TSLA,339.16,494.26,2184,Tech,237482.0,841.981795,True,True
...,...,...,...,...,...,...,...,...,...,...
95,2024-04-05,GOOG,114.75,471.33,5070,Tech,525721.5,1863.921618,True,True
96,2024-04-06,GOOG,343.83,271.27,1580,Tech,94293.5,334.313148,False,False
97,2024-04-07,AMZN,301.07,486.66,8004,Automotive,856949.9,3038.276779,True,True
98,2024-04-08,GOOG,120.59,485.45,9130,Tech,975074.9,3457.083630,True,True
99,2024-04-09,AAPL,211.46,441.20,4147,Automotive,402524.4,1427.131992,True,True

In [ ]:
# creating a new column
data["Totalt"] = data["Netto"] + data["Avgift"] 
# applying a function on a column data
data["Category"] = data["Years"].apply(lambda x: "Young" if x < 30 else "Adult")
data