In [2]:
import pandas as pd
# data input and df creation
data=pd.read_csv("Assignment_11_data.csv")
data = data.set_index("Date")
data

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

# Nivå 1 – Grunderna

In [17]:
## 1. Visa de första 5 rader
data.head()

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-17,TX001,Customer01,296.97,Entertainment,39,6.244998,6.2
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-05-24,TX004,Customer04,295.20,Electronics,14,3.741657,3.7
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1

In [18]:
## 2. Visa de sista 5 raderna
data.tail()

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-06,TX016,Customer16,89.21,Electronics,28,5.291503,5.3
2025-04-27,TX017,Customer17,59.10,Entertainment,31,5.567764,5.6
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1

In [17]:
## 3. Visa information om tabellen
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  20 non-null     str
 1   Customer        20 non-null     str
 2   Amount          20 non-null     float64
 3   Category        20 non-null     str
 4   Date            20 non-null     str
dtypes: float64(1), str(4)
memory usage: 932.0 bytes

In [19]:
## 4. Visa kolumnens namn
data.columns

Index(['Transaction_ID', 'Customer', 'Amount', 'Category', 'Price',
       'root of price', 'Root of price'],
      dtype='str')

In [20]:
## 5. Visa kategorier för alla köp
data["Category"]

Date
2025-05-17    Entertainment
2025-05-23        Utilities
2025-05-03         Clothing
2025-05-24      Electronics
2025-04-28         Clothing
2025-04-29         Clothing
2025-05-05        Utilities
2025-05-16      Electronics
2025-05-11         Clothing
2025-05-09         Clothing
2025-05-23    Entertainment
2025-05-15         Clothing
2025-05-13      Electronics
2025-05-16        Utilities
2025-05-07        Utilities
2025-05-06      Electronics
2025-04-27    Entertainment
2025-05-20    Entertainment
2025-05-09    Entertainment
2025-05-11    Entertainment
Name: Category, dtype: str

In [21]:
## 6. Visa kategorier och belopp för alla köp
data[["Category","Amount"]]

                 Category  Amount
Date
2025-05-17  Entertainment  296.97
2025-05-23      Utilities  371.84
2025-05-03       Clothing  321.24
2025-05-24    Electronics  295.20
2025-04-28       Clothing  240.64
2025-04-29       Clothing  340.65
2025-05-05      Utilities  246.91
2025-05-16    Electronics  451.30
2025-05-11       Clothing  483.65
2025-05-09       Clothing  222.55
2025-05-23  Entertainment  406.28
2025-05-15       Clothing  288.00
2025-05-13    Electronics  305.62
2025-05-16      Utilities  466.52
2025-05-07      Utilities   81.97
2025-05-06    Electronics   89.21
2025-04-27  Entertainment   59.10
2025-05-20  Entertainment  424.68
2025-05-09  Entertainment  400.17
2025-05-11  Entertainment  441.51

In [22]:
## 7. Hur många köp djordes?
len(data)

20

In [39]:
## 8. Visa köp med ett enstaka nummer
print(data.iloc[0])    # 1-a

Transaction_ID            TX001
Customer             Customer01
Amount                   296.97
Category          Entertainment
Date                 2025-05-17
Name: 0, dtype: object

In [23]:
## 9. Hitta alla köp av kläder
data.loc[data["Category"] == "Clothing"]

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1
2025-04-29,TX006,Customer06,340.65,Clothing,26,5.099020,5.1
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-09,TX010,Customer10,222.55,Clothing,24,4.898979,4.9
2025-05-15,TX012,Customer12,288.00,Clothing,11,3.316625,3.3

In [24]:
## 10. Hitta alla köp för mer än 350 y.e.
data.loc[data["Amount"] > 350]

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1

In [25]:
## Flera villkor samtidigt
# 11. När för underhållninhgen betalades mer än 400 y.e?
data.loc[(data["Category"] == "Entertainment") & (data["Amount"] > 400)]

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1

In [32]:
## Flera villkor samtidigt
# 12. Vilka köpare köpte elektronikprylar?
data.loc[data["Category"] == "Electronics", ["Customer", "Category"]]

              Customer     Category
Date
2025-05-24  Customer04  Electronics
2025-05-16  Customer08  Electronics
2025-05-13  Customer13  Electronics
2025-05-06  Customer16  Electronics

In [28]:
## 13.Om du vill hitta något ord i hela tabellen, inte bara en kolumn
# För att hitta rader som innehåller något:data.loc[data["kolumn"].str.contains("text")]
data.loc[data.astype(str).apply(lambda x: x.str.contains("020")).any(axis=1)]

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.09902,5.1

In [29]:
## 14. Visa statistik
round(data.describe(),2)

       Amount  Price  root of price  Root of price
count   20.00  20.00          20.00          20.00
mean   311.70  26.00           4.95           4.95
std    127.39  12.44           1.25           1.25
min     59.10  10.00           3.16           3.20
25%    245.34  14.75           3.84           3.85
50%    313.43  26.00           5.10           5.10
75%    410.88  37.50           6.12           6.12
max    483.65  47.00           6.86           6.90

# Nivå 2 – Filtrering

In [16]:
## 15. Köp för mer än 450 y.e
#print("Köp för mer än 450 y.e:\n", data[data["Amount"] > 450],"\n")
data[data["Amount"] > 450]

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5

In [13]:
## 16. Köp av accessoarer
print(" \nAccessoarer:\n", data[data["Category"] == "Utilities"],"\n")

Accessoarer:
            Transaction_ID    Customer  Amount   Category  Price  \
Date
2025-05-23          TX002  Customer02  371.84  Utilities     16
2025-05-05          TX007  Customer07  246.91  Utilities     29
2025-05-16          TX014  Customer14  466.52  Utilities     42
2025-05-07          TX015  Customer15   81.97  Utilities     10

            root of price  Root of price
Date
2025-05-23       4.000000            4.0
2025-05-05       5.385165            5.4
2025-05-16       6.480741            6.5
2025-05-07       3.162278            3.2

In [50]:
## 17. Köp som inte underhållning
not_underhållning=data[data["Category"] != "Entertainment "]
print(not_underhållning)

   Transaction_ID    Customer  Amount       Category        Date
0           TX001  Customer01  296.97  Entertainment  2025-05-17
1           TX002  Customer02  371.84      Utilities  2025-05-23
2           TX003  Customer03  321.24       Clothing  2025-05-03
3           TX004  Customer04  295.20    Electronics  2025-05-24
4           TX005  Customer05  240.64       Clothing  2025-04-28
5           TX006  Customer06  340.65       Clothing  2025-04-29
6           TX007  Customer07  246.91      Utilities  2025-05-05
7           TX008  Customer08  451.30    Electronics  2025-05-16
8           TX009  Customer09  483.65       Clothing  2025-05-11
9           TX010  Customer10  222.55       Clothing  2025-05-09
10          TX011  Customer11  406.28  Entertainment  2025-05-23
11          TX012  Customer12  288.00       Clothing  2025-05-15
12          TX013  Customer13  305.62    Electronics  2025-05-13
13          TX014  Customer14  466.52      Utilities  2025-05-16
14          TX015  Customer15   81.97      Utilities  2025-05-07
15          TX016  Customer16   89.21    Electronics  2025-05-06
16          TX017  Customer17   59.10  Entertainment  2025-04-27
17          TX018  Customer18  424.68  Entertainment  2025-05-20
18          TX019  Customer19  400.17  Entertainment  2025-05-09
19          TX020  Customer20  441.51  Entertainment  2025-05-11

# Nivå 3 – Sortering och analys

In [33]:
## 18. Sortera efter beloppet
data.sort_values("Amount")

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-04-27,TX017,Customer17,59.10,Entertainment,31,5.567764,5.6
2025-05-07,TX015,Customer15,81.97,Utilities,10,3.162278,3.2
2025-05-06,TX016,Customer16,89.21,Electronics,28,5.291503,5.3
2025-05-09,TX010,Customer10,222.55,Clothing,24,4.898979,4.9
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1
2025-05-05,TX007,Customer07,246.91,Utilities,29,5.385165,5.4
2025-05-15,TX012,Customer12,288.00,Clothing,11,3.316625,3.3
2025-05-24,TX004,Customer04,295.20,Electronics,14,3.741657,3.7
2025-05-17,TX001,Customer01,296.97,Entertainment,39,6.244998,6.2
2025-05-13,TX013,Customer13,305.62,Electronics,10,3.162278,3.2
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-04-29,TX006,Customer06,340.65,Clothing,26,5.099020,5.1
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9

In [34]:
## 19. Sortera efter datumet
data.sort_values("Date")

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-04-27,TX017,Customer17,59.10,Entertainment,31,5.567764,5.6
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1
2025-04-29,TX006,Customer06,340.65,Clothing,26,5.099020,5.1
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-05-05,TX007,Customer07,246.91,Utilities,29,5.385165,5.4
2025-05-06,TX016,Customer16,89.21,Electronics,28,5.291503,5.3
2025-05-07,TX015,Customer15,81.97,Utilities,10,3.162278,3.2
2025-05-09,TX010,Customer10,222.55,Clothing,24,4.898979,4.9
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-13,TX013,Customer13,305.62,Electronics,10,3.162278,3.2
2025-05-15,TX012,Customer12,288.00,Clothing,11,3.316625,3.3
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9
2025-05-17,TX001,Customer01,296.97,Entertainment,39,6.244998,6.2
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-24,TX004,Customer04,295.20,Electronics,14,3.741657,3.7

In [35]:
## 20. Sortera efter priset
data.sort_values("Price")

,Transaction_ID,Customer,Amount,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-13,TX013,Customer13,305.62,Electronics,10,3.162278,3.2
2025-05-07,TX015,Customer15,81.97,Utilities,10,3.162278,3.2
2025-05-15,TX012,Customer12,288.00,Clothing,11,3.316625,3.3
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-05-24,TX004,Customer04,295.20,Electronics,14,3.741657,3.7
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-09,TX010,Customer10,222.55,Clothing,24,4.898979,4.9
2025-04-29,TX006,Customer06,340.65,Clothing,26,5.099020,5.1
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1
2025-05-06,TX016,Customer16,89.21,Electronics,28,5.291503,5.3
2025-05-05,TX007,Customer07,246.91,Utilities,29,5.385165,5.4
2025-04-27,TX017,Customer17,59.10,Entertainment,31,5.567764,5.6
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1
2025-05-17,TX001,Customer01,296.97,Entertainment,39,6.244998,6.2
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9

In [36]:
## 21. Medelpriset 
print("Medelpriset för alla köp:", round(data["Price"].mean(),1))

Medelpriset för alla köp: 26.0

In [38]:
## 22. Dyraste köp
print("Dyraste köp:", data["Amount"].max())

Dyraste köp: 483.65

In [39]:
## 23. Billigaste köp
print("Billigaste köp:",data["Amount"].min())

Billigaste köp: 59.1

In [40]:
## 24. Dyraste priset
print("Dyraste priset:", data["Price"].max())

Dyraste priset: 47

In [41]:
## 23. Billigaste priset
print("Billigaste priset:",data["Price"].min())

Billigaste priset: 10

# Nivå 4 – Skapa kolumner

In [44]:
# data cleaning
data = data.dropna()                     # remove missing rows
data["Amount"] = data["Amount"].fillna(0)      # fill missing values
data = data.drop_duplicates()
data = data.rename(columns={"Amount": "Totalt"})
data

,Transaction_ID,Customer,Totalt,Category,Price,root of price,Root of price
Date,,,,,,,
2025-05-17,TX001,Customer01,296.97,Entertainment,39,6.244998,6.2
2025-05-23,TX002,Customer02,371.84,Utilities,16,4.000000,4.0
2025-05-03,TX003,Customer03,321.24,Clothing,12,3.464102,3.5
2025-05-24,TX004,Customer04,295.20,Electronics,14,3.741657,3.7
2025-04-28,TX005,Customer05,240.64,Clothing,37,6.082763,6.1
2025-04-29,TX006,Customer06,340.65,Clothing,26,5.099020,5.1
2025-05-05,TX007,Customer07,246.91,Utilities,29,5.385165,5.4
2025-05-16,TX008,Customer08,451.30,Electronics,47,6.855655,6.9
2025-05-11,TX009,Customer09,483.65,Clothing,15,3.872983,3.9
2025-05-09,TX010,Customer10,222.55,Clothing,24,4.898979,4.9
2025-05-23,TX011,Customer11,406.28,Entertainment,41,6.403124,6.4
2025-05-15,TX012,Customer12,288.00,Clothing,11,3.316625,3.3
2025-05-13,TX013,Customer13,305.62,Electronics,10,3.162278,3.2
2025-05-16,TX014,Customer14,466.52,Utilities,42,6.480741,6.5
2025-05-07,TX015,Customer15,81.97,Utilities,10,3.162278,3.2
2025-05-06,TX016,Customer16,89.21,Electronics,28,5.291503,5.3
2025-04-27,TX017,Customer17,59.10,Entertainment,31,5.567764,5.6
2025-05-20,TX018,Customer18,424.68,Entertainment,44,6.633250,6.6
2025-05-09,TX019,Customer19,400.17,Entertainment,18,4.242641,4.2
2025-05-11,TX020,Customer20,441.51,Entertainment,26,5.099020,5.1

# Nivå 5 – Grupp och riktig analys

In [3]:
# köp, nummer 3 till 10 inklusive
data.iloc[2:10]

           Transaction_ID    Customer  Amount     Category
Date
2025-05-03          TX003  Customer03  321.24     Clothing
2025-05-24          TX004  Customer04  295.20  Electronics
2025-04-28          TX005  Customer05  240.64     Clothing
2025-04-29          TX006  Customer06  340.65     Clothing
2025-05-05          TX007  Customer07  246.91    Utilities
2025-05-16          TX008  Customer08  451.30  Electronics
2025-05-11          TX009  Customer09  483.65     Clothing
2025-05-09          TX010  Customer10  222.55     Clothing

In [4]:
# köp, enstaka datumet
data.loc[["2025-04-29","2025-05-09"]]

           Transaction_ID    Customer  Amount       Category
Date
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-09          TX019  Customer19  400.17  Entertainment

In [6]:
# adding new data 
import numpy as np
data["Price"] = np.random.randint(10,50,20) #slumptal mellan 10 och 50 med steg 20
data["Price"]

Date
2025-05-17    39
2025-05-23    16
2025-05-03    12
2025-05-24    14
2025-04-28    37
2025-04-29    26
2025-05-05    29
2025-05-16    47
2025-05-11    15
2025-05-09    24
2025-05-23    41
2025-05-15    11
2025-05-13    10
2025-05-16    42
2025-05-07    10
2025-05-06    28
2025-04-27    31
2025-05-20    44
2025-05-09    18
2025-05-11    26
Name: Price, dtype: int32

In [8]:
# filtering
import pandas as pd
# data input and df creation
data=pd.read_csv("Assignment_11_data.csv")
data = data.set_index("Date")
data
data[(data["Amount"] > 300) & (data["Price"] < 40)]

KeyError: 'Price'

In [6]:
import numpy as np
data["Root of price"] = round(data["Price"].apply(lambda x: np.sqrt(x)),1)
data

NameError: name 'data' is not defined

In [2]:
data.groupby("Category")["Entertainment"].mean()

NameError: name 'data' is not defined

In [1]:
data.groupby("Category")["Entertainment"].mean()
#data.groupby("Years")[["Salary", "Age_plus_10"]].agg(["mean", "max", "min"])
data

NameError: name 'data' is not defined