In [2]:
import pandas as pd
# data input and df creation
data=pd.read_csv("Assignment_11_data.csv")
data = data.set_index("Date")
data

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

# Nivå 1 – Grunderna

In [24]:
## 1. Visa de första 5 rader
data.head()

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing

In [25]:
## 2. Visa de sista 5 raderna
data.tail()

           Transaction_ID    Customer  Amount       Category
Date
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

In [26]:
## 3. Visa information om tabellen
data.info()

<class 'pandas.DataFrame'>
Index: 20 entries, 2025-05-17 to 2025-05-11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  20 non-null     str
 1   Customer        20 non-null     str
 2   Amount          20 non-null     float64
 3   Category        20 non-null     str
dtypes: float64(1), str(3)
memory usage: 1.3+ KB

In [27]:
## 4. Visa kolumnens namn
data.columns

Index(['Transaction_ID', 'Customer', 'Amount', 'Category'], dtype='str')

In [28]:
## 5. Visa kategorier för alla köp
data["Category"]

Date
2025-05-17    Entertainment
2025-05-23        Utilities
2025-05-03         Clothing
2025-05-24      Electronics
2025-04-28         Clothing
2025-04-29         Clothing
2025-05-05        Utilities
2025-05-16      Electronics
2025-05-11         Clothing
2025-05-09         Clothing
2025-05-23    Entertainment
2025-05-15         Clothing
2025-05-13      Electronics
2025-05-16        Utilities
2025-05-07        Utilities
2025-05-06      Electronics
2025-04-27    Entertainment
2025-05-20    Entertainment
2025-05-09    Entertainment
2025-05-11    Entertainment
Name: Category, dtype: str

In [29]:
## 6. Visa kategorier och belopp för alla köp
data[["Category","Amount"]]

                 Category  Amount
Date
2025-05-17  Entertainment  296.97
2025-05-23      Utilities  371.84
2025-05-03       Clothing  321.24
2025-05-24    Electronics  295.20
2025-04-28       Clothing  240.64
2025-04-29       Clothing  340.65
2025-05-05      Utilities  246.91
2025-05-16    Electronics  451.30
2025-05-11       Clothing  483.65
2025-05-09       Clothing  222.55
2025-05-23  Entertainment  406.28
2025-05-15       Clothing  288.00
2025-05-13    Electronics  305.62
2025-05-16      Utilities  466.52
2025-05-07      Utilities   81.97
2025-05-06    Electronics   89.21
2025-04-27  Entertainment   59.10
2025-05-20  Entertainment  424.68
2025-05-09  Entertainment  400.17
2025-05-11  Entertainment  441.51

In [30]:
## 7. Hur många köp djordes?
len(data)

20

In [31]:
## 8. Visa köp med ett enstaka nummer
print(data.iloc[0])    # 1-a

Transaction_ID            TX001
Customer             Customer01
Amount                   296.97
Category          Entertainment
Name: 2025-05-17, dtype: object

In [32]:
## 9. Hitta alla köp av kläder
data.loc[data["Category"] == "Clothing"]

           Transaction_ID    Customer  Amount  Category
Date
2025-05-03          TX003  Customer03  321.24  Clothing
2025-04-28          TX005  Customer05  240.64  Clothing
2025-04-29          TX006  Customer06  340.65  Clothing
2025-05-11          TX009  Customer09  483.65  Clothing
2025-05-09          TX010  Customer10  222.55  Clothing
2025-05-15          TX012  Customer12  288.00  Clothing

In [33]:
## 10. Hitta alla köp för mer än 350 y.e.
data.loc[data["Amount"] > 350]

           Transaction_ID    Customer  Amount       Category
Date
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

In [34]:
## Flera villkor samtidigt
# 11. När för underhållninhgen betalades mer än 400 y.e?
data.loc[(data["Category"] == "Entertainment") & (data["Amount"] > 400)]

           Transaction_ID    Customer  Amount       Category
Date
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

In [35]:
## Flera villkor samtidigt
# 12. Vilka köpare köpte elektronikprylar?
data.loc[data["Category"] == "Electronics", ["Customer", "Category"]]

              Customer     Category
Date
2025-05-24  Customer04  Electronics
2025-05-16  Customer08  Electronics
2025-05-13  Customer13  Electronics
2025-05-06  Customer16  Electronics

In [36]:
## 13.Om du vill hitta något ord i hela tabellen, inte bara en kolumn
# För att hitta rader som innehåller något:data.loc[data["kolumn"].str.contains("text")]
data.loc[data.astype(str).apply(lambda x: x.str.contains("020")).any(axis=1)]

           Transaction_ID    Customer  Amount       Category
Date
2025-05-11          TX020  Customer20  441.51  Entertainment

In [37]:
## 14. Visa statistik
round(data.describe(),2)

       Amount
count   20.00
mean   311.70
std    127.39
min     59.10
25%    245.34
50%    313.43
75%    410.88
max    483.65

# Nivå 2 – Filtrering

In [38]:
## 15. Köp för mer än 450 y.e
#print("Köp för mer än 450 y.e:\n", data[data["Amount"] > 450],"\n")
data[data["Amount"] > 450]

           Transaction_ID    Customer  Amount     Category
Date
2025-05-16          TX008  Customer08  451.30  Electronics
2025-05-11          TX009  Customer09  483.65     Clothing
2025-05-16          TX014  Customer14  466.52    Utilities

In [39]:
## 16. Köp av accessoarer
print(" \nAccessoarer:\n", data[data["Category"] == "Utilities"],"\n")

Accessoarer:
            Transaction_ID    Customer  Amount   Category
Date
2025-05-23          TX002  Customer02  371.84  Utilities
2025-05-05          TX007  Customer07  246.91  Utilities
2025-05-16          TX014  Customer14  466.52  Utilities
2025-05-07          TX015  Customer15   81.97  Utilities

In [40]:
## 17. Köp som inte underhållning
not_underhållning=data[data["Category"] != "Entertainment "]
print(not_underhållning)

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

# Nivå 3 – Sortering och analys

In [41]:
## 18. Sortera efter beloppet
data.sort_values("Amount")

           Transaction_ID    Customer  Amount       Category
Date
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-05-09          TX010  Customer10  222.55       Clothing
2025-04-28          TX005  Customer05  240.64       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-03          TX003  Customer03  321.24       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-11          TX009  Customer09  483.65       Clothing

In [42]:
## 19. Sortera efter datumet
data.sort_values("Date")

           Transaction_ID    Customer  Amount       Category
Date
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-24          TX004  Customer04  295.20    Electronics

In [43]:
## 20. Sortera efter priset
#data.sort_values("Price")

In [45]:
## 21. Medelpriset 
#print("Medelpriset för alla köp:", round(data["Price"].mean(),1))

In [46]:
## 22. Dyraste köp
print("Dyraste köp:", data["Amount"].max())

Dyraste köp: 483.65

In [47]:
## 23. Billigaste köp
print("Billigaste köp:",data["Amount"].min())

Billigaste köp: 59.1

In [49]:
## 24. Dyraste priset
#print("Dyraste priset:", data["Price"].max())

In [41]:
## 23. Billigaste priset
print("Billigaste priset:",data["Price"].min())

Billigaste priset: 10

# Nivå 4 – Skapa kolumner

In [50]:
# data cleaning
data = data.dropna()                     # remove missing rows
data["Amount"] = data["Amount"].fillna(0)      # fill missing values
data = data.drop_duplicates()
data = data.rename(columns={"Amount": "Totalt"})
data

           Transaction_ID    Customer  Totalt       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

# Nivå 5 – Grupp och riktig analys

In [51]:
# köp, nummer 3 till 10 inklusive
data.iloc[2:10]

           Transaction_ID    Customer  Totalt     Category
Date
2025-05-03          TX003  Customer03  321.24     Clothing
2025-05-24          TX004  Customer04  295.20  Electronics
2025-04-28          TX005  Customer05  240.64     Clothing
2025-04-29          TX006  Customer06  340.65     Clothing
2025-05-05          TX007  Customer07  246.91    Utilities
2025-05-16          TX008  Customer08  451.30  Electronics
2025-05-11          TX009  Customer09  483.65     Clothing
2025-05-09          TX010  Customer10  222.55     Clothing

In [52]:
# köp, enstaka datumet
data.loc[["2025-04-29","2025-05-09"]]

           Transaction_ID    Customer  Totalt       Category
Date
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-09          TX019  Customer19  400.17  Entertainment

In [54]:
# adding new data 
import numpy as np
data["Price"] = np.random.randint(10,50,20) #slumptal mellan 10 och 50 med steg 20
data["Price"] 
data

           Transaction_ID    Customer  Totalt       Category  Price
Date
2025-05-17          TX001  Customer01  296.97  Entertainment     28
2025-05-23          TX002  Customer02  371.84      Utilities     40
2025-05-03          TX003  Customer03  321.24       Clothing     46
2025-05-24          TX004  Customer04  295.20    Electronics     24
2025-04-28          TX005  Customer05  240.64       Clothing     40
2025-04-29          TX006  Customer06  340.65       Clothing     23
2025-05-05          TX007  Customer07  246.91      Utilities     28
2025-05-16          TX008  Customer08  451.30    Electronics     22
2025-05-11          TX009  Customer09  483.65       Clothing     40
2025-05-09          TX010  Customer10  222.55       Clothing     14
2025-05-23          TX011  Customer11  406.28  Entertainment     49
2025-05-15          TX012  Customer12  288.00       Clothing     37
2025-05-13          TX013  Customer13  305.62    Electronics     18
2025-05-16          TX014  Customer14  466.52      Utilities     18
2025-05-07          TX015  Customer15   81.97      Utilities     15
2025-05-06          TX016  Customer16   89.21    Electronics     17
2025-04-27          TX017  Customer17   59.10  Entertainment     18
2025-05-20          TX018  Customer18  424.68  Entertainment     17
2025-05-09          TX019  Customer19  400.17  Entertainment     36
2025-05-11          TX020  Customer20  441.51  Entertainment     25

In [55]:
# filtering
data[(data["Totalt"] > 300) & (data["Price"] < 40)]

           Transaction_ID    Customer  Totalt       Category  Price
Date
2025-04-29          TX006  Customer06  340.65       Clothing     23
2025-05-16          TX008  Customer08  451.30    Electronics     22
2025-05-13          TX013  Customer13  305.62    Electronics     18
2025-05-16          TX014  Customer14  466.52      Utilities     18
2025-05-20          TX018  Customer18  424.68  Entertainment     17
2025-05-09          TX019  Customer19  400.17  Entertainment     36
2025-05-11          TX020  Customer20  441.51  Entertainment     25

In [56]:
import numpy as np
data["Root of price"] = round(data["Price"].apply(lambda x: np.sqrt(x)),1)
data

,Transaction_ID,Customer,Totalt,Category,Price,Root of price
Date,,,,,,
2025-05-17,TX001,Customer01,296.97,Entertainment,28,5.3
2025-05-23,TX002,Customer02,371.84,Utilities,40,6.3
2025-05-03,TX003,Customer03,321.24,Clothing,46,6.8
2025-05-24,TX004,Customer04,295.20,Electronics,24,4.9
2025-04-28,TX005,Customer05,240.64,Clothing,40,6.3
2025-04-29,TX006,Customer06,340.65,Clothing,23,4.8
2025-05-05,TX007,Customer07,246.91,Utilities,28,5.3
2025-05-16,TX008,Customer08,451.30,Electronics,22,4.7
2025-05-11,TX009,Customer09,483.65,Clothing,40,6.3
2025-05-09,TX010,Customer10,222.55,Clothing,14,3.7
2025-05-23,TX011,Customer11,406.28,Entertainment,49,7.0
2025-05-15,TX012,Customer12,288.00,Clothing,37,6.1
2025-05-13,TX013,Customer13,305.62,Electronics,18,4.2
2025-05-16,TX014,Customer14,466.52,Utilities,18,4.2
2025-05-07,TX015,Customer15,81.97,Utilities,15,3.9
2025-05-06,TX016,Customer16,89.21,Electronics,17,4.1
2025-04-27,TX017,Customer17,59.10,Entertainment,18,4.2
2025-05-20,TX018,Customer18,424.68,Entertainment,17,4.1
2025-05-09,TX019,Customer19,400.17,Entertainment,36,6.0
2025-05-11,TX020,Customer20,441.51,Entertainment,25,5.0

In [58]:
data.groupby("Category")["Entertainment"].mean()

KeyError: 'Column not found: Entertainment'

In [1]:
data.groupby("Category")["Entertainment"].mean()
#data.groupby("Years")[["Salary", "Age_plus_10"]].agg(["mean", "max", "min"])
data

NameError: name 'data' is not defined