In [1]:
import pandas as pd

In [16]:
# data input and df creation

df = pd.read_csv(r"data/Assignment_11_data.csv")

df = df.set_index("Date")
df

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-23          TX011  Customer11  406.28  Entertainment
2025-05-15          TX012  Customer12  288.00       Clothing
2025-05-13          TX013  Customer13  305.62    Electronics
2025-05-16          TX014  Customer14  466.52      Utilities
2025-05-07          TX015  Customer15   81.97      Utilities
2025-05-06          TX016  Customer16   89.21    Electronics
2025-04-27          TX017  Customer17   59.10  Entertainment
2025-05-20          TX018  Customer18  424.68  Entertainment
2025-05-09          TX019  Customer19  400.17  Entertainment
2025-05-11          TX020  Customer20  441.51  Entertainment

In [19]:
# using iloc()
df.iloc[0:10]

           Transaction_ID    Customer  Amount       Category
Date
2025-05-17          TX001  Customer01  296.97  Entertainment
2025-05-23          TX002  Customer02  371.84      Utilities
2025-05-03          TX003  Customer03  321.24       Clothing
2025-05-24          TX004  Customer04  295.20    Electronics
2025-04-28          TX005  Customer05  240.64       Clothing
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-05          TX007  Customer07  246.91      Utilities
2025-05-16          TX008  Customer08  451.30    Electronics
2025-05-11          TX009  Customer09  483.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing

In [21]:
df.loc[["2025-04-29","2025-05-09"]]

           Transaction_ID    Customer  Amount       Category
Date
2025-04-29          TX006  Customer06  340.65       Clothing
2025-05-09          TX010  Customer10  222.55       Clothing
2025-05-09          TX019  Customer19  400.17  Entertainment

In [30]:
# adding new data 
import numpy as np
df["Price"] = np.random.randint(10,50,20)

           Transaction_ID    Customer  Amount       Category  Price
Date
2025-05-17          TX001  Customer01  296.97  Entertainment     27
2025-05-23          TX002  Customer02  371.84      Utilities     36
2025-05-03          TX003  Customer03  321.24       Clothing     24
2025-05-24          TX004  Customer04  295.20    Electronics     17
2025-04-28          TX005  Customer05  240.64       Clothing     11
2025-04-29          TX006  Customer06  340.65       Clothing     37
2025-05-05          TX007  Customer07  246.91      Utilities     46
2025-05-16          TX008  Customer08  451.30    Electronics     12
2025-05-11          TX009  Customer09  483.65       Clothing     31
2025-05-09          TX010  Customer10  222.55       Clothing     37
2025-05-23          TX011  Customer11  406.28  Entertainment     22
2025-05-15          TX012  Customer12  288.00       Clothing     30
2025-05-13          TX013  Customer13  305.62    Electronics     14
2025-05-16          TX014  Customer14  466.52      Utilities     21
2025-05-07          TX015  Customer15   81.97      Utilities     41
2025-05-06          TX016  Customer16   89.21    Electronics     45
2025-04-27          TX017  Customer17   59.10  Entertainment     15
2025-05-20          TX018  Customer18  424.68  Entertainment     33
2025-05-09          TX019  Customer19  400.17  Entertainment     46
2025-05-11          TX020  Customer20  441.51  Entertainment     13

In [47]:
# filtering
df[(df["Amount"] > 200) & (df["Price"] < 40)]

           Transaction_ID    Customer  Amount       Category  Price
Date
2025-05-17          TX001  Customer01  296.97  Entertainment     27
2025-05-23          TX002  Customer02  371.84      Utilities     36
2025-05-03          TX003  Customer03  321.24       Clothing     24
2025-05-24          TX004  Customer04  295.20    Electronics     17
2025-04-28          TX005  Customer05  240.64       Clothing     11
2025-04-29          TX006  Customer06  340.65       Clothing     37
2025-05-16          TX008  Customer08  451.30    Electronics     12
2025-05-11          TX009  Customer09  483.65       Clothing     31
2025-05-09          TX010  Customer10  222.55       Clothing     37
2025-05-23          TX011  Customer11  406.28  Entertainment     22
2025-05-15          TX012  Customer12  288.00       Clothing     30
2025-05-13          TX013  Customer13  305.62    Electronics     14
2025-05-16          TX014  Customer14  466.52      Utilities     21
2025-05-20          TX018  Customer18  424.68  Entertainment     33
2025-05-11          TX020  Customer20  441.51  Entertainment     13

In [49]:
import numpy as np
df["root of price"] = df["Price"].apply(lambda x: np.sqrt(x) )
df

,Transaction_ID,Customer,Amount,Category,Price,root of price
Date,,,,,,
2025-05-17,TX001,Customer01,296.97,Entertainment,27,5.196152
2025-05-23,TX002,Customer02,371.84,Utilities,36,6.000000
2025-05-03,TX003,Customer03,321.24,Clothing,24,4.898979
2025-05-24,TX004,Customer04,295.20,Electronics,17,4.123106
2025-04-28,TX005,Customer05,240.64,Clothing,11,3.316625
2025-04-29,TX006,Customer06,340.65,Clothing,37,6.082763
2025-05-05,TX007,Customer07,246.91,Utilities,46,6.782330
2025-05-16,TX008,Customer08,451.30,Electronics,12,3.464102
2025-05-11,TX009,Customer09,483.65,Clothing,31,5.567764
2025-05-09,TX010,Customer10,222.55,Clothing,37,6.082763
2025-05-23,TX011,Customer11,406.28,Entertainment,22,4.690416
2025-05-15,TX012,Customer12,288.00,Clothing,30,5.477226
2025-05-13,TX013,Customer13,305.62,Electronics,14,3.741657
2025-05-16,TX014,Customer14,466.52,Utilities,21,4.582576
2025-05-07,TX015,Customer15,81.97,Utilities,41,6.403124
2025-05-06,TX016,Customer16,89.21,Electronics,45,6.708204
2025-04-27,TX017,Customer17,59.10,Entertainment,15,3.872983
2025-05-20,TX018,Customer18,424.68,Entertainment,33,5.744563
2025-05-09,TX019,Customer19,400.17,Entertainment,46,6.782330
2025-05-11,TX020,Customer20,441.51,Entertainment,13,3.605551